repos:
#  - repo: https://github.com/golangci/golangci-lint
#    rev: v1.42.1
#    hooks:
#      - id: golangci-lint
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
#    - id: golangci-lint

